# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Andre P. Oliveira"
tagline:          'An Adventure in Mathematics'
description:      'I am a Ph. D. candidate in Mathematics at Wesleyan University, working under the supervision of <a href="http://framirez.web.wesleyan.edu">Felipe A. Ramirez</a>.'
research:         "My research is primarily focused in homegeneous dynamics and its applications to Diophantine approximations. In particular, I'm interested in $p$-adic analogues of Diophantine approximation results."
url:              "http://andrepoliveira.com/"
baseurl:          ""

blogbaseurl:      "/blog/"

google_analytics: 'UA-56467618-1'

author:
  name:           'Andre P. Oliveira'
  email:          'aoliveira (at) wesleyan (dot) edu'

paginate:         5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
