# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Andre P. Oliveira"
tagline:          'An Adventure in Mathematics'
description:      'I am currently in my third year of graduate work at Wesleyan University, working under the supervision of <a href="http://framirez.web.wesleyan.edu">Felipe A. Ramirez</a>.'
url:              "http://andrepoliveira.com/"
baseurl:          ""

blogbaseurl:      "/blog/"

google_analytics: 'UA-56467618-1'

author:
  name:           'Andre P. Oliveira'
  email:          'aoliveira (at) wesleyan (dot) edu'

paginate:         5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-seo-tag
