# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Andre P. Oliveira"
tagline:          'An Adventure in Mathematics'
description:      'I am a Ph. D. candidate in Mathematics at Wesleyan University, working under the supervision of <a href="http://framirez.web.wesleyan.edu">Felipe A. Ramírez</a>.'
research:         "My research is primarily focused in Metric Number Theory from a Diophantine approximations perspective. I am particularly interested in the connections and interplay between real and p-adic Diophantine approximation."
url:              "https://andrepoliveira.com"
baseurl:          ""

blogbaseurl:      "/blog/"

google_analytics: 'UA-56467618-1'

author:
  name:           'Andre P. Oliveira'
  email:          'aoliveira (at) wesleyan (dot) edu'

paginate:         5
paginate_path: "/blog/page:num"

defaults: 
  -
    scope: 
      path: ""
      type: "posts"
    values:
      image: "/public/images/fountain_pen.jpg"
  -
    scope: 
      path: ""
      type: "pages"
    values:
      image: "/public/images/portrait.jpg"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

exclude: ["Gemfile", "package-lock.json", "makefile", "prepyaml.js", "template.tex", "res.cls", "node_modules"]
