# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Andre P. Oliveira"
tagline:          'An Adventure in Mathematics'
description:      "I am currently a Data Science Intern at Travelers Insurance. Before that, I received my Ph.D. in Mathematics. Currently exploring and enjoying the world of Industry."
research:         "My academic research is primarily focused in Metric Number Theory from a Diophantine approximations perspective. I am particularly interested in the connections and interplay between real and p-adic Diophantine approximation."
url:              "https://andrepoliveira.com"
baseurl:          ""

blogbaseurl:      "/blog/"

umami_analytics_id: '59b405e7-6119-4f48-9235-4b1fd1860e9e'

author:
  name:           'Andre P. Oliveira'
  email:          "'oliveira.andrepinto' on GMail"

paginate:         5
paginate_path: "/blog/page:num"

defaults: 
  -
    scope: 
      path: ""
      type: "posts"
    values:
      image: "/public/images/fountain_pen.jpg"
  -
    scope: 
      path: ""
      type: "pages"
    values:
      image: "/public/images/portrait.jpg"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

exclude: ["Gemfile", "package-lock.json", "makefile", "prepyaml.js", "template.tex", "res.cls", "node_modules"]
