- title: Co-Organizer
  organization: Graduate Student Seminar
  date: December 2019 -- present 
- title: Treasurer
  organization: AMS Local Graduate Student Chapter
  date: July 2019 -- present
- title: Co-organizer
  organization: Directed Reading Program
  date: Sep. 2018 -- present 
- title: Webmaster
  organization: Graduate Student Association
  date: May 2017 -- present 
- title: Graduate Community Standards Board member
  organization: Graduate Student Association
  date: May 2017 -- Sep. 2018 
- title: President
  organization: AMS Local Graduate Student Chapter
  date: Aug. 2016 -- July 2019
